# Generated by Django 5.1.2 on 2025-01-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_mediafile_delete_qrcodemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='media',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='qr_code',
            field=models.ImageField(blank=True, default=1, upload_to='qrcodes/'),
            preserve_default=False,
        ),
    ]
